<?php
    $features = array(
                      'caravans', //New
                        //'caravans_addnl',
                        'toilets',
                        //'toilets_addnl',
                        'disableFacility',
                        //'disableFacility_addnl',
                        'showers',
                        //'showers_addnl',
                        'drinkingWater',
                        //'drinkingWater_addnl',
                        'drinkingWaterNotSuitable',
                        //'drinkingWaterNotSuitable_addnl',
                        'waterFillingAvailable',    //New
                        //'waterFillingAvailable_addnl',
                        'wasteFacilityAvailable',
                        //'wasteFacilityAvailable_addnl',
                        'dumpPointAvailable',
                        //'dumpPointAvailable_addnl',
                        'poweredSites',
                        //'poweredSites_addnl',
                        'emergencyPhone',
                        //'emergencyPhone_addnl',
                        'mobilePhoneReception',
                        //'mobilePhoneReception_addnl',
                        'petsOk',
                        //'petsOk_addnl',
                        'petsNotOk',
                        //'petsNotOk_addnl',
                        'fourWheelDrive',
                        //'fourWheelDrive_addnl',
                        'dryWeatherOnlyAccess',
                        //'dryWeatherOnlyAccess_addnl',
                        'tentsOnly',
                        //'tentsOnly_addnl',
                        'noTents',  //New
                        //'noTents_addnl',
                        'camperTrailers',   //New
                        //'camperTrailers_addnl',
                        'noCamperTrailers', //New
                        //'noCamperTrailers_addnl',
                        'largeSizeMotohomeAccess',
                        //'largeSizeMotohomeAccess_addnl',
                        'bigrig',
                        'bigrig_addnl',
                        'selfContainedVehicles',
                        //'selfContainedVehicles_addnl',
                        'onSiteAccomodation', //New
                        //'onSiteAccomodation_addnl',
                        //'rvTurnAroundArea',
                        //'rvTurnAroundArea_addnl',
                        //'rvParkingAvailable',
                        //'rvParkingAvailable_addnl',
                        'boatRamp',
                        //'boatRamp_addnl',
                        'timeLimitApplies',
                        //'timeLimitApplies_addnl',
                        'shadedSites',
                        //'shadedSites_addnl',
                        'firePit',
                        //'firePit_addnl',
                        'noFirePit',  //New
                        //'noFirePit_addnl',
                        'picnicTable',
                        //'picnicTable_addnl',
                        'bbq',
                        //'bbq_addnl',
                        'shelter',
                        //'shelter_addnl',
                        'childrenPlayground',
                        //'childrenPlayground_addnl',
                        'views',
                        //'views_addnl',
                        'parkFees',
                        //'parkFees_addnl',
                        //'parking',                       
                        //'parking_addnl', //95
                        //new additions for role 7
                        'campKitchen', 
                        //'campKitchen_addnl',
                        'laundry',
                        //'laundry_addnl',
                        'ensuiteSites',
                        //'ensuiteSites_addnl',
                        'restaurant',
                        //'restaurant_addnl',
                        'kiosk',
                        //'kiosk_addnl',
                        'internetAccess',
                        //'internetAccess_addnl',
                        'swimmingPool',
                        //'swimmingPool_addnl',
                        'gamesRoom',
                        //'gamesRoom_addnl',
                        'generatorsPermitted',
                        //'generatorsPermitted_addnl',
                        'generatorsNotPermitted',
                        //'generatorsNotPermitted_addnl',
                        'showGrounds',  //New
                        //'showGrounds_addnl',
                        'nationalParknForestry',    //New
                        //'nationalParknForestry_addnl',
                        'pubs', //New
                        //'pubs_addnl',   
                        'sharedWithTrucks', //New
                        //'sharedWithTrucks_addnl', 
                  );
?>